// ==UserScript==
// @name         Congerie Better UI for Torn
// @namespace    https://github.com/congeriesstudio-wq/better-ui
// @version      2.0.0
// @description  Responsive visual redesign for Torn on desktop, tablet, phone, and Torn PDA.
// @match        https://www.torn.com/*
// @run-at       document-end
// @grant        none
// @updateURL    https://raw.githubusercontent.com/congeriesstudio-wq/better-ui/main/congerie-torn-ui.user.js
// @downloadURL  https://raw.githubusercontent.com/congeriesstudio-wq/better-ui/main/congerie-torn-ui.user.js
// ==/UserScript==

(() => {
'use strict';
const ROOT='cg-ui-v2', STYLE='cg-ui-v2-style';
if(document.documentElement.dataset.cgUiV2)return;
document.documentElement.dataset.cgUiV2='1';

const css=`
:root{--cg-bg:#0b1016;--cg-bg2:#0e151d;--cg-surface:#121a23;--cg-surface2:#17212c;--cg-border:rgba(255,255,255,.075);--cg-border2:rgba(255,255,255,.12);--cg-text:#eef3f8;--cg-text2:#c2ccd6;--cg-muted:#7f8b99;--cg-blue:#5da7ff;--cg-blue-soft:rgba(93,167,255,.12);--cg-green:#59cf91;--cg-red:#ed7373;--cg-yellow:#e6bd64;--cg-radius:10px;--cg-top:54px;--cg-side:226px;--cg-bottom:54px}
html,body{background:var(--cg-bg)!important;color:var(--cg-text)!important}html{color-scheme:dark}body,body *{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif!important}body{min-height:100vh!important;background:radial-gradient(900px 500px at 48% -18%,rgba(72,126,183,.10),transparent 70%),linear-gradient(180deg,#0c1219 0%,#0b1016 100%)!important}
a{transition:color .15s ease,opacity .15s ease,background .15s ease!important}button,input[type=button],input[type=submit],input[type=reset],select,textarea,input:not([type=checkbox]):not([type=radio]){font:inherit!important}button,input[type=button],input[type=submit],input[type=reset]{border-radius:7px!important;transition:transform .12s ease,filter .15s ease,background .15s ease,border-color .15s ease!important}button:hover,input[type=button]:hover,input[type=submit]:hover,input[type=reset]:hover{filter:brightness(1.08)}button:active,input[type=button]:active,input[type=submit]:active,input[type=reset]:active{transform:translateY(1px)}input:not([type=checkbox]):not([type=radio]),textarea,select{background:#0d141c!important;color:var(--cg-text)!important;border:1px solid var(--cg-border2)!important;border-radius:7px!important;box-shadow:none!important}input:not([type=checkbox]):not([type=radio]):focus,textarea:focus,select:focus{outline:none!important;border-color:rgba(93,167,255,.55)!important;box-shadow:0 0 0 3px var(--cg-blue-soft)!important}table{border-collapse:separate!important;border-spacing:0!important;overflow:hidden!important;border:1px solid var(--cg-border)!important;border-radius:var(--cg-radius)!important;background:var(--cg-surface)!important}table th{background:var(--cg-surface2)!important;color:var(--cg-text2)!important}table td,table th{border-color:var(--cg-border)!important}tbody tr:hover{background:rgba(255,255,255,.018)!important}*{scrollbar-width:thin;scrollbar-color:#344251 transparent}*::-webkit-scrollbar{width:8px;height:8px}*::-webkit-scrollbar-track{background:transparent}*::-webkit-scrollbar-thumb{background:#344251;border-radius:99px}
#cg-v2-root{position:fixed;inset:0;z-index:2147483000;pointer-events:none}#cg-v2-root *{box-sizing:border-box}
.cg-v2-top{position:fixed;top:0;left:0;right:0;height:var(--cg-top);display:flex;align-items:center;gap:14px;padding:0 18px;background:rgba(10,15,21,.97);border-bottom:1px solid var(--cg-border2);box-shadow:0 8px 28px rgba(0,0,0,.18);pointer-events:auto}.cg-v2-brand{display:flex;align-items:center;gap:10px;min-width:190px;color:#f4f8fc;text-decoration:none}.cg-v2-logo{width:31px;height:31px;display:grid;place-items:center;border:1px solid rgba(93,167,255,.32);border-radius:8px;background:linear-gradient(145deg,rgba(93,167,255,.18),rgba(93,167,255,.04));color:var(--cg-blue);font-size:11px;font-weight:850;letter-spacing:-.05em}.cg-v2-brand-text{display:block;font-size:13px;font-weight:750}.cg-v2-brand-sub{display:block;margin-top:1px;color:#667484;font-size:9px}.cg-v2-search{width:min(360px,36vw);height:34px;display:flex;align-items:center;gap:8px;padding:0 11px;border:1px solid var(--cg-border);border-radius:8px;background:#0d141b;color:#687787;font-size:11px}.cg-v2-top-spacer{flex:1}.cg-v2-top-actions{display:flex;align-items:center;gap:6px}.cg-v2-top-actions button,.cg-v2-menu-button{width:34px;height:34px;padding:0;border:1px solid transparent;border-radius:8px;background:transparent;color:#8b99a8;cursor:pointer}.cg-v2-top-actions button:hover,.cg-v2-menu-button:hover{background:rgba(255,255,255,.05);color:#eaf1f8}.cg-v2-menu-button{display:none}
.cg-v2-side{position:fixed;top:var(--cg-top);left:0;bottom:var(--cg-bottom);width:var(--cg-side);padding:12px;overflow-y:auto;background:rgba(13,19,26,.98);border-right:1px solid var(--cg-border);pointer-events:auto}.cg-v2-player{margin-bottom:10px;padding:13px;border:1px solid var(--cg-border);border-radius:var(--cg-radius);background:linear-gradient(160deg,#151e27,#111820)}.cg-v2-player-head{display:flex;align-items:center;gap:10px}.cg-v2-avatar{width:36px;height:36px;flex:0 0 36px;display:grid;place-items:center;border-radius:9px;background:#202d3a;color:#dce8f4;font-size:12px;font-weight:800;overflow:hidden}.cg-v2-avatar img{width:100%;height:100%;object-fit:cover}.cg-v2-player-name{color:#edf3f9;font-size:12px;font-weight:700}.cg-v2-player-meta{margin-top:2px;color:#788697;font-size:10px}.cg-v2-bars{margin-top:12px;display:grid;gap:7px}.cg-v2-bar{display:grid;grid-template-columns:45px 1fr 37px;align-items:center;gap:7px;color:#8d9aa9;font-size:9px}.cg-v2-track{height:5px;overflow:hidden;border-radius:99px;background:#252f3a}.cg-v2-fill{display:block;height:100%;width:60%;border-radius:inherit;background:var(--cg-blue)}.cg-v2-section-label{margin:14px 7px 6px;color:#596778;font-size:9px;font-weight:800;letter-spacing:.11em;text-transform:uppercase}.cg-v2-nav{display:grid;gap:2px}.cg-v2-nav a{min-height:34px;display:flex;align-items:center;gap:9px;padding:0 9px;border:1px solid transparent;border-radius:7px;color:#9aa6b5;text-decoration:none;font-size:11px;font-weight:600}.cg-v2-nav a:hover{color:#f1f6fb;background:rgba(255,255,255,.045)}.cg-v2-nav a.cg-current{color:#f3f7fb;background:var(--cg-blue-soft);border-color:rgba(93,167,255,.11)}.cg-v2-nav a.cg-current:before{content:'';width:3px;height:15px;margin-left:-10px;border-radius:99px;background:var(--cg-blue)}.cg-v2-nav-icon{width:18px;text-align:center;color:#6e7c8c;font-size:11px}.cg-v2-nav a:hover .cg-v2-nav-icon,.cg-v2-nav a.cg-current .cg-v2-nav-icon{color:var(--cg-blue)}
.cg-v2-main{position:fixed;top:var(--cg-top);left:var(--cg-side);right:0;bottom:var(--cg-bottom);overflow:auto;padding:24px 26px 28px;pointer-events:none}.cg-v2-main-inner{max-width:1260px;margin:0 auto}.cg-v2-pagebar{min-height:50px;display:flex;align-items:center;gap:14px;margin-bottom:14px}.cg-v2-page-title{color:#f1f5f9;font-size:22px;font-weight:750;letter-spacing:-.025em}.cg-v2-page-sub{margin-top:3px;color:#748292;font-size:11px}.cg-v2-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.cg-v2-card{min-height:84px;padding:16px;border:1px solid var(--cg-border);border-radius:var(--cg-radius);background:rgba(18,26,35,.88)}
.cg-v2-bottom{position:fixed;left:var(--cg-side);right:0;bottom:0;height:var(--cg-bottom);display:flex;align-items:center;gap:7px;padding:7px 14px;background:rgba(10,15,21,.98);border-top:1px solid var(--cg-border);pointer-events:auto;overflow-x:auto}.cg-v2-bottom a{min-width:112px;height:38px;display:flex;align-items:center;gap:8px;padding:0 11px;border:1px solid var(--cg-border);border-radius:8px;background:#141d26;color:#b7c1cb;text-decoration:none;font-size:10px;font-weight:650}.cg-v2-bottom a:hover{border-color:var(--cg-border2);color:#fff;background:#19232e}
@media(max-width:980px){:root{--cg-side:0px;--cg-bottom:58px}.cg-v2-side{transform:translateX(-100%);width:min(290px,86vw);box-shadow:18px 0 40px rgba(0,0,0,.35);transition:transform .2s ease;z-index:5}.cg-v2-side.open,#cg-v2-root.cg-nav-open .cg-v2-side{transform:translateX(0)}.cg-v2-menu-button{display:block}.cg-v2-brand{min-width:0}.cg-v2-search{display:none}.cg-v2-main{padding:18px 14px 22px}.cg-v2-bottom{left:0}}
@media(max-width:680px){:root{--cg-top:50px}.cg-v2-top{padding:0 10px;gap:8px}.cg-v2-brand-text{font-size:12px}.cg-v2-brand-sub{display:none}.cg-v2-logo{width:28px;height:28px}.cg-v2-top-actions button{width:31px;height:31px}.cg-v2-page-title{font-size:19px}.cg-v2-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.cg-v2-card{padding:13px}.cg-v2-bottom{padding:6px 8px;gap:6px}.cg-v2-bottom a{min-width:86px;justify-content:center;padding:0 9px}}
@media(max-width:430px){.cg-v2-main{padding:14px 10px 18px}.cg-v2-grid{grid-template-columns:1fr}.cg-v2-pagebar{min-height:44px}.cg-v2-bottom a{min-width:72px;font-size:9px}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;transition-duration:.01ms!important}}
`;
const style=document.createElement('style');style.id=STYLE;style.textContent=css;document.head.appendChild(style);

const root=document.createElement('div');root.id=ROOT;root.innerHTML=`
<header class="cg-v2-top"><button class="cg-v2-menu-button" type="button" aria-label="Open navigation">☰</button><a class="cg-v2-brand" href="/" aria-label="Home"><span class="cg-v2-logo">CG</span><span><span class="cg-v2-brand-text">CONGERIE</span><span class="cg-v2-brand-sub">TORN INTERFACE</span></span></a><div class="cg-v2-search"><span>⌕</span><span>Search Torn...</span></div><div class="cg-v2-top-spacer"></div><div class="cg-v2-top-actions"><button type="button" aria-label="Notifications">●</button><button type="button" aria-label="Profile">◎</button><button type="button" aria-label="Settings">⚙</button></div></header>
<aside class="cg-v2-side"><div class="cg-v2-player"><div class="cg-v2-player-head"><div class="cg-v2-avatar">U</div><div><div class="cg-v2-player-name">Player</div><div class="cg-v2-player-meta">Level — · Online</div></div></div><div class="cg-v2-bars"><div class="cg-v2-bar"><span>Energy</span><span class="cg-v2-track"><i class="cg-v2-fill" data-bar="energy"></i></span><b data-stat="energy">—</b></div><div class="cg-v2-bar"><span>Nerve</span><span class="cg-v2-track"><i class="cg-v2-fill" data-bar="nerve"></i></span><b data-stat="nerve">—</b></div><div class="cg-v2-bar"><span>Happy</span><span class="cg-v2-track"><i class="cg-v2-fill" data-bar="happy"></i></span><b data-stat="happy">—</b></div><div class="cg-v2-bar"><span>Life</span><span class="cg-v2-track"><i class="cg-v2-fill" data-bar="life"></i></span><b data-stat="life">—</b></div></div></div><div class="cg-v2-section-label">Navigation</div><nav class="cg-v2-nav" data-nav></nav><div class="cg-v2-section-label">Quick access</div><nav class="cg-v2-nav" data-nav-quick></nav></aside>
<main class="cg-v2-main"><div class="cg-v2-main-inner"><div class="cg-v2-pagebar"><div><div class="cg-v2-page-title" data-page-title>TORN</div><div class="cg-v2-page-sub" data-page-sub>City interface</div></div></div><div class="cg-v2-grid" aria-hidden="true"><div class="cg-v2-card"></div><div class="cg-v2-card"></div><div class="cg-v2-card"></div></div></div></main><nav class="cg-v2-bottom" data-bottom></nav>`;
document.body.appendChild(root);

document.body.classList.add('cg-v2-active');
const path=location.pathname.toLowerCase(), query=new URLSearchParams(location.search), sid=(query.get('sid')||'').toLowerCase();
const links=[['⌂','Home','/'],['◉','Profile','/profiles.php'],['⌂','City','/city.php'],['⚔','Battle','/loader.php?sid=attack'],['▣','Items','/item.php'],['◈','Market','/market.php'],['⚑','Faction','/factions.php'],['◆','Job','/joblist.php'],['✦','Education','/education.php'],['✈','Travel','/travelagency.php'],['▤','Forums','/forums.php'],['✉','Messages','/messages.php']];
const quick=[['⌂','Hospital','/hospitalview.php'],['▣','Jail','/jailview.php'],['♟','Missions','/missions.php'],['★','Hall of Fame','/hof.php'],['◒','Casino','/casino.php'],['⚙','Preferences','/preferences.php']];
const bottom=[['⌂','Home','/'],['⌁','City','/city.php'],['▣','Items','/item.php'],['⚔','Battle','/loader.php?sid=attack'],['☰','More','#cg-more']];
const makeLink=([icon,label,href])=>{const a=document.createElement('a');a.href=href;a.innerHTML=`<span class="cg-v2-nav-icon">${icon}</span><span>${label}</span>`;return a};
links.forEach(x=>root.querySelector('[data-nav]').appendChild(makeLink(x)));quick.forEach(x=>root.querySelector('[data-nav-quick]').appendChild(makeLink(x)));bottom.forEach(x=>root.querySelector('[data-bottom]').appendChild(makeLink(x)));

const titles=[['/city.php','City','Explore Torn City'],['/profiles.php','Profile','Player profile'],['/item.php','Items','Inventory and equipment'],['/market.php','Market','Buy and sell'],['/factions.php','Faction','Faction management'],['/joblist.php','Job','Career and workplace'],['/education.php','Education','Courses and training'],['/travelagency.php','Travel','Destinations and flights'],['/forums.php','Forums','Community discussions'],['/messages.php','Messages','Inbox and communications'],['/hospitalview.php','Hospital','Current medical status'],['/jailview.php','Jail','Current jail status'],['/missions.php','Missions','Active missions'],['/hof.php','Hall of Fame','Rankings'],['/casino.php','Casino','Games and gambling'],['/preferences.php','Preferences','Account settings']];
const match=titles.find(x=>path.includes(x[0]));root.querySelector('[data-page-title]').textContent=match?match[1]:(sid==='attack'?'Battle':'Torn');root.querySelector('[data-page-sub]').textContent=match?match[2]:(sid==='attack'?'Combat interface':'City interface');

function markActive(){root.querySelectorAll('.cg-v2-nav a').forEach(a=>{a.classList.remove('cg-current');const href=a.getAttribute('href')||'';const p=href.split('?')[0];if((p==='/'&&location.pathname==='/')||(p!=='/'&&p===location.pathname))a.classList.add('cg-current')})}
markActive();
root.querySelector('.cg-v2-menu-button').addEventListener('click',()=>root.classList.toggle('cg-nav-open'));
root.querySelectorAll('.cg-v2-side a').forEach(a=>a.addEventListener('click',()=>root.classList.remove('cg-nav-open')));

function clean(s){return(s||'').replace(/\s+/g,' ').trim()}
function sync(){
const text=clean(document.body.innerText);const level=text.match(/Level:\s*(\d+)/i);const money=text.match(/Money:\s*\$?([\d,]+)/i);const name=text.match(/Name:\s*([^\n]+?)(?=\s+Money:)/i);if(name)root.querySelector('.cg-v2-player-name').textContent=name[1].trim();if(level)root.querySelector('.cg-v2-player-meta').textContent=`Level ${level[1]} · ${money?'$'+money[1]:'Online'}`;
[['energy',/Energy:\s*([\d,]+)\s*\/\s*([\d,]+)/i],['nerve',/Nerve:\s*([\d,]+)\s*\/\s*([\d,]+)/i],['happy',/Happy:\s*([\d,]+)\s*\/\s*([\d,]+)/i],['life',/Life:\s*([\d,]+)\s*\/\s*([\d,]+)/i]].forEach(([k,re])=>{const m=text.match(re);if(!m)return;const a=Number(m[1].replace(/,/g,'')),b=Number(m[2].replace(/,/g,'')),pct=b?Math.max(0,Math.min(100,a/b*100)):0;const v=root.querySelector(`[data-stat="${k}"]`),f=root.querySelector(`[data-bar="${k}"]`);if(v)v.textContent=`${m[1]}/${m[2]}`;if(f)f.style.width=pct+'%'})}
sync();
let timer=0;const observer=new MutationObserver(()=>{if(timer)return;timer=requestAnimationFrame(()=>{timer=0;sync();markActive()})});observer.observe(document.body,{childList:true,subtree:true,characterData:true});
})();
